# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r}
setwd("C:/Users/jf08/RepData_PeerAssessment1")
unzip("activity.zip")
activity <- read.csv("activity.csv", header=T, sep=",", quote="\"")
head(activity)
```

## What is mean total number of steps taken per day?

```{r fig.width=7, fig.height=6}
# Calculate the total number of steps taken each day
stepsumD <- aggregate(steps~date, data=activity, FUN="sum")
# Display total number of steps each day with histogram
hist(stepsumD$steps)
# Compute mean of total number of steps each day
mean(stepsumD$steps)
# Compute median of total number of steps each day
median(stepsumD$steps)
```

## What is the average daily activity pattern?
```{r fig.width=7, fig.height=6}
# Calculate the average number of steps taken versus 5-minute interval and display a few of them
stepAveInt <- aggregate(steps~interval, data=activity, FUN="mean")
head(stepAveInt)
# Display the average number of steps taken versus 5-minute interval with time series plot
plot(stepAveInt$interval, stepAveInt$steps, type='l', xlab="interval", ylab="Average steps", main="Changes in average steps of intervals during a day", col=1,axes=T)
# Find the time series containing the maximum number of steps and report it
subset(stepAveInt, steps==max(stepAveInt$steps))
subset(stepAveInt, steps==max(stepAveInt$steps))$interval

# Calculate summary stats for the average number of steps taken versus 5-minute interval
summary(stepAveInt$steps)
```

## Imputing missing values

```{r fig.width=7, fig.height=6}
# Check how many steps with missing value
length(activity[activity$steps=="NA",]$steps)

# Imputing strategy: If missing value, using the average number of steps for that time interval to replace the missing value
# Merge the raw data with aggregating data (average number of steps for each interval)
activity1 <- merge(activity, stepAveInt, by="interval")
# Go through raw data set steps, if it's NA, then it will be replaced by aggreated average number of steps of that time interval
for(i in 1:nrow(activity1)){
  if(is.na(activity1$steps.x[i])){
    activity1$steps.x[i]<-activity1$steps.y[i]
  }
}
# Check a few records after imputing data
head(activity1, 10)
# Get and prepare new dataframe with imputated steps, date and interval, assign the column names
activity2<-data.frame(activity1$steps.x, activity1$date, activity1$interval)
colnames(activity2)<-c("steps","date","interval")
# Calculate the total number of steps taken each day again after missing data values were imputed, display that with histogram, calculate mean, median again.
stepsumD2 <- aggregate(steps~date, data=activity2, FUN="sum")
hist(stepsumD2$steps)
mean(stepsumD2$steps)
median(stepsumD2$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r fig.width=7, fig.height=6}
# Add new variable wd, assign as weekend or weekday based on date situation, added that to previous dataframe, display a few records of the dataframe
wd<-weekdays(as.Date(activity2$date))
for(i in 1:length(wd)){
  if(wd[i]=="Saturday" | wd[i]=="Sunday"){
    wd[i]<-"weekend"
  }else{
    wd[i]<-"weekday"
  }
}
activity2$weekday<-wd
head(activity2)
# Compute average nubmer of steps taken based on time series interval and weekdays, display a few records
stepAveInt1 <- aggregate(steps~interval+weekday, data=activity2, FUN="mean")
head(stepAveInt1)
# Display the average number of steps taken versus 5-minute interval and weekday with time series plot, using lattice package
library(lattice)
stepAveInt1<-transform(stepAveInt1, weekday=factor(weekday))
xyplot(steps~interval|weekday, data=stepAveInt1, layout=c(1,2), lty=1, type="l")

```
